[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:OMNI3D_MMS]
command=/app/OMNI3D_MMS/main
directory=/app/OMNI3D_MMS
autostart=true
autorestart=true
startretries=10
startsecs=5
stdout_logfile=/var/log/OMNI3D_MMS.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
stderr_logfile=/var/log/OMNI3D_MMS.err
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=2
environment=HOME="/root"

[program:OMNI3D_RFID_Middleware]
command=/app/OMNI3D_RFID_Middleware/main
directory=/app/OMNI3D_RFID_Middleware
autostart=true
autorestart=true
startretries=10
startsecs=5
stdout_logfile=/var/log/OMNI3D_RFID_Middleware.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
stderr_logfile=/var/log/OMNI3D_RFID_Middleware.err
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=2
environment=HOME="/root"

[program:OMNI3D_Template]
command=/app/OMNI3D_Template/main
directory=/app/OMNI3D_Template
autostart=true
autorestart=true
startretries=10
startsecs=5
stdout_logfile=/var/log/OMNI3D_Template.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
stderr_logfile=/var/log/OMNI3D_Template.err
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=2
environment=HOME="/root"

[program:OMNI3D_Work_Time_Counter]
command=/app/OMNI3D_Work_Time_Counter/main
directory=/app/OMNI3D_Work_Time_Counter
autostart=true
autorestart=true
startretries=10
startsecs=5
stdout_logfile=/var/log/OMNI3D_Work_Time_Counter.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
stderr_logfile=/var/log/OMNI3D_Work_Time_Counter.err
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=2
environment=HOME="/root"
