[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

COPY OMNI3D_MMS/src/ /build/OMNI3D_MMS/
RUN pyinstaller /build/OMNI3D_MMS/main.py --onedir -y \
    --name OMNI3D_MMS \
    --distpath /app \
    --collect-all omnode \
    --collect-all fastapi \
    --collect-all uvicorn

COPY OMNI3D_RFID_Middleware/src/ /build/OMNI3D_RFID_Middleware/
RUN pyinstaller /build/OMNI3D_RFID_Middleware/main.py --onedir -y \
    --name OMNI3D_RFID_Middleware \
    --distpath /app \
    --collect-all omnode \
    --collect-all fastapi \
    --collect-all uvicorn

COPY OMNI3D_Template/src/ /build/OMNI3D_Template/
RUN pyinstaller /build/OMNI3D_Template/main.py --onedir -y \
    --name OMNI3D_Template \
    --distpath /app \
    --collect-all omnode \
    --collect-all fastapi \
    --collect-all uvicorn

COPY OMNI3D_Work_Time_Counter/src/ /build/OMNI3D_Work_Time_Counter/
RUN pyinstaller /build/OMNI3D_Work_Time_Counter/main.py --onedir -y \
    --name OMNI3D_Work_Time_Counter \
    --distpath /app \
    --collect-all omnode \
    --collect-all fastapi \
    --collect-all uvicorn
