#!/usr/bin/env python3
"""
Dynamically generates Dockerfile and supervisord.conf
based on service submodules present in the workspace.

A service submodule is any directory that:
  - has a src/ directory
  - has at least one .py file in src/ (excluding __init__.py)
  - is NOT a config repo (*_Config)
  - is NOT omnode (OMNI3D_omnode)
  - is NOT omni3d-container
  - is NOT a firmware repo (RRF_Environment)
"""

import os
import sys
import json

SKIP_DIRS = {"omni3d-container", "OMNI3D_omnode", "RRF_Environment", "O3D_Bootloader"}

def find_services(workspace):
    services = []
    for d in sorted(os.listdir(workspace)):
        path = os.path.join(workspace, d)
        if not os.path.isdir(path):
            continue
        if d in SKIP_DIRS:
            continue
        if d.endswith("_Config"):
            continue
        if d.startswith("."):
            continue
        src = os.path.join(path, "src")
        if not os.path.isdir(src):
            continue
        # entry point must be main.py
        if not os.path.exists(os.path.join(src, "main.py")):
            print(f"── Skipping {d} — no main.py found in src/ ──")
            continue
        entry = "main.py"
        binary = entry.replace(".py", "")
        services.append({
            "dir":    d,
            "entry":  entry,
            "binary": binary,
        })
        print(f"── Found service: {d} → src/{entry} ──")
    return services


def generate_dockerfile(services):
    lines = [
        "# Dockerfile — auto-generated by generate_config.py",
        "# DO NOT EDIT MANUALLY",
        "",
        "FROM python:3.11-slim",
        "",
        "# ── system dependencies ──────────────────────────────────────────────",
        "RUN apt-get update && apt-get install -y \\",
        "    binutils \\",
        "    supervisor \\",
        "    libz-dev \\",
        "    git \\",
        "    python3-apt \\",
        "    && rm -rf /var/lib/apt/lists/*",
        "",
        "# ── build and install omnode ─────────────────────────────────────────",
        "COPY OMNI3D_omnode/ /build/OMNI3D_omnode/",
        "COPY omni3d-container/requirements.txt /tmp/requirements.txt",
        "RUN SETUPTOOLS_SCM_PRETEND_VERSION=0.0.1 pip install --no-cache-dir /build/OMNI3D_omnode/ && \\",
        "    pip install --no-cache-dir -r /tmp/requirements.txt && \\",
        "    pip install --no-cache-dir pyinstaller",
        "",
        "# ── build service binaries ───────────────────────────────────────────",
        "RUN mkdir -p /app",
        "WORKDIR /build",
        "",
    ]

    for svc in services:
        lines += [
            f"COPY {svc['dir']}/src/ /build/{svc['dir']}/",
            f"RUN COLLECT=$(grep -v '^#' /tmp/requirements.txt | grep -v '^$' | cut -d= -f1 | sed 's/.*/ --collect-all &/' | tr -d '\\n') && \\",
            f"    pyinstaller /build/{svc['dir']}/{svc['entry']} --onedir -y $COLLECT \\",
            f"    --hidden-import apt \\",
            f"    --hidden-import apt_pkg \\",
            f"    && mv /build/dist/main /app/{svc['dir']}",
            "",
        ]

    lines += [
        "# ── machine config ──────────────────────────────────────────────────",
        "ARG CONFIG_DIR=OMNIPRO_Config",
        "ARG FIRMWARE_DIR=RRF_Environment",
        "COPY ${CONFIG_DIR}/src/macros /app/config/macros",
        "COPY ${CONFIG_DIR}/src/sys    /app/config/sys",
        "RUN mkdir -p /app/firmware",
        "COPY ${FIRMWARE_DIR}/firmware/ /app/firmware/ 2>/dev/null || true",
        "",
        "# ── deploy config script ─────────────────────────────────────────────",
        "COPY omni3d-container/deploy_config.sh /app/deploy_config.sh",
        "RUN chmod +x /app/deploy_config.sh",
        "",
        "# ── supervisord config ───────────────────────────────────────────────",
        "COPY omni3d-container/supervisord.conf /etc/supervisor/conf.d/omni3d.conf",
        "",
        "EXPOSE 5000-5005",
        "",
        "# ── expose ports ───────────────────────────────────────────────────────",
        "EXPOSE 5000-5005",
        "",
        "WORKDIR /app",
        'CMD ["/bin/bash", "-c", "/app/deploy_config.sh && /usr/bin/supervisord -n -c /etc/supervisor/conf.d/omni3d.conf"]',
    ]

    return "\n".join(lines)


def generate_supervisord(services):
    lines = [
        "[supervisord]",
        "nodaemon=true",
        "logfile=/var/log/supervisord.log",
        "logfile_maxbytes=10MB",
        "logfile_backups=3",
        "loglevel=info",
        "",
        "[unix_http_server]",
        "file=/var/run/supervisor.sock",
        "",
        "[supervisorctl]",
        "serverurl=unix:///var/run/supervisor.sock",
        "",
        "[rpcinterface:supervisor]",
        "supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface",
        "",
    ]

    for svc in services:
        lines += [
            f"[program:{svc['dir']}]",
            f"command=/app/{svc['dir']}/main",
            f"directory=/app/{svc['dir']}",
            "autostart=true",
            "autorestart=true",
            "startretries=10",
            "startsecs=5",
            f"stdout_logfile=/var/log/{svc['dir']}.log",
            "stdout_logfile_maxbytes=5MB",
            "stdout_logfile_backups=2",
            f"stderr_logfile=/var/log/{svc['dir']}.err",
            "stderr_logfile_maxbytes=5MB",
            "stderr_logfile_backups=2",
            'environment=HOME="/root"',
            "",
        ]

    return "\n".join(lines)


if __name__ == "__main__":
    workspace = sys.argv[1] if len(sys.argv) > 1 else "."
    services = find_services(workspace)

    if not services:
        print("ERROR: No service submodules found")
        sys.exit(1)

    print(f"\n── Found {len(services)} services: {[s['dir'] for s in services]} ──\n")

    dockerfile = generate_dockerfile(services)
    supervisord = generate_supervisord(services)

    with open("omni3d-container/Dockerfile", "w") as f:
        f.write(dockerfile)
    print("── Generated omni3d-container/Dockerfile ──")

    with open("omni3d-container/supervisord.conf", "w") as f:
        f.write(supervisord)
    print("── Generated omni3d-container/supervisord.conf ──")

    # write services manifest for CI use
    with open("omni3d-container/.services.json", "w") as f:
        json.dump(services, f, indent=2)
    print(f"── Written .services.json: {[s['dir'] for s in services]} ──")
